### ISSUE TITLE
no way relation error

### ISSUE THREAD

**Issue by bmatusiak** [fabrik42/node_tile_server#1]
{ [error: relation "ways" does not exist]
  length: 96,
  name: 'error',
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '118',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'parse_relation.c',
  line: '864',
  routine: 'parserOpenTable' }

do you know the problem by chance?

**Comment by fabrik42** [comment]
It seems like you didn't load the OSM dataset into your database?

**Comment by bmatusiak** [comment]
http://download.geofabrik.de/north-america/us/florida-latest.osm.pbf

is the OSM dataset i was using..    i tested with  nominatim

**Comment by fabrik42** [comment]
You can see the db statement here:

https://github.com/fabrik42/node_tile_server/blob/master/src/tile_modes/osm_streets/way_collection.coffee#L86

how the server fetches the ways from the database. It uses the default osmosis DB schema, as described here: http://wiki.openstreetmap.org/wiki/Osmosis/PostGIS_Setup

If you want to use another schema, you have to change the SQL queries accordingly.

**Comment by fabrik42** [comment]
Closing this for now.
